"""initial schema

Revision ID: 499f067d6536
Revises: 
Create Date: 2026-04-13 10:57:00.859822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '499f067d6536'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment', sa.Enum('shk', 'elektro', 'dach_holz', 'metallbau', 'geruestbau', 'landschaftsbau', 'general', name='segment', native_enum=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('datanorm_id', sa.String(), nullable=True),
    sa.Column('unit', sa.Enum('hours', 'pieces', 'meters', 'kg', 'liters', 'sqm', 'flat_rate', name='unit', native_enum=False), nullable=False),
    sa.Column('default_price', sa.Numeric(), nullable=False),
    sa.Column('wholesaler', sa.String(), nullable=True),
    sa.Column('last_price_date', sa.Date(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firm',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('segment', sa.Enum('shk', 'elektro', 'dach_holz', 'metallbau', 'geruestbau', 'landschaftsbau', 'general', name='segment', native_enum=False), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name='fk_firm_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment', sa.Enum('shk', 'elektro', 'dach_holz', 'metallbau', 'geruestbau', 'landschaftsbau', 'general', name='segment', native_enum=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('avg_duration_h', sa.Numeric(), nullable=True),
    sa.Column('avg_margin_pct', sa.Numeric(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['job_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_article_price_history_lookup', 'article_price_history', ['article_id', 'recorded_at'], unique=False)
    op.create_table('cl_benchmark',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type_id', sa.UUID(), nullable=False),
    sa.Column('segment', sa.Enum('shk', 'elektro', 'dach_holz', 'metallbau', 'geruestbau', 'landschaftsbau', 'general', name='segment', native_enum=False), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('metric', sa.Enum('duration_h', 'margin_pct', 'material_cost', 'quote_total', 'conversion_rate', name='cl_metric', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('p25', sa.Numeric(), nullable=False),
    sa.Column('p50', sa.Numeric(), nullable=False),
    sa.Column('p75', sa.Numeric(), nullable=False),
    sa.Column('mean', sa.Numeric(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_type_id'], ['job_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cl_benchmark_lookup', 'cl_benchmark', ['job_type_id', 'segment', 'region', 'metric', 'currency'], unique=False)
    op.create_table('firm_benchmark',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('job_type_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.Enum('duration_h', 'margin_pct', 'material_cost', 'quote_total', 'conversion_rate', name='cl_metric', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('p25', sa.Numeric(), nullable=True),
    sa.Column('p50', sa.Numeric(), nullable=True),
    sa.Column('p75', sa.Numeric(), nullable=True),
    sa.Column('mean', sa.Numeric(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.ForeignKeyConstraint(['job_type_id'], ['job_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_firm_benchmark_lookup', 'firm_benchmark', ['firm_id', 'job_type_id', 'metric'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('meister', 'geselle', 'buero', name='role', native_enum=False), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('residential', 'commercial', 'public', name='customer_type', native_enum=False), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('quote', 'quote_line_item', 'project', 'project_line_item', name='event_entity_type', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'updated', 'status_changed', 'deleted', name='event_type', native_enum=False), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_actor', 'event', ['actor_id'], unique=False)
    op.create_index('idx_event_entity', 'event', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_event_time', 'event', ['created_at'], unique=False)
    op.create_table('quote',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('job_type_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'accepted', 'rejected', 'expired', name='quote_status', native_enum=False), nullable=False),
    sa.Column('total_net', sa.Numeric(), nullable=True),
    sa.Column('total_gross', sa.Numeric(), nullable=True),
    sa.Column('margin_target', sa.Numeric(), nullable=True),
    sa.Column('cl_margin_pred', sa.Numeric(), nullable=True),
    sa.Column('cl_price_bench', sa.Numeric(), nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('accepted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('rejected_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.ForeignKeyConstraint(['job_type_id'], ['job_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('job_type_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', 'cancelled', name='project_status', native_enum=False), nullable=False),
    sa.Column('planned_hours', sa.Numeric(), nullable=True),
    sa.Column('actual_hours', sa.Numeric(), nullable=True),
    sa.Column('planned_cost', sa.Numeric(), nullable=True),
    sa.Column('actual_cost', sa.Numeric(), nullable=True),
    sa.Column('margin_pct', sa.Numeric(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.ForeignKeyConstraint(['job_type_id'], ['job_type.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_line_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('labor', 'material', 'other', name='line_category', native_enum=False), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.Enum('hours', 'pieces', 'meters', 'kg', 'liters', 'sqm', 'flat_rate', name='unit', native_enum=False), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=False),
    sa.Column('total', sa.Numeric(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('cl_price_flag', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_line_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('quote_line_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('labor', 'material', 'other', name='line_category', native_enum=False), nullable=False),
    sa.Column('actual_quantity', sa.Numeric(), nullable=False),
    sa.Column('actual_unit_price', sa.Numeric(), nullable=False),
    sa.Column('actual_total', sa.Numeric(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_by', sa.UUID(), nullable=True),
    sa.Column('logged_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['logged_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['quote_line_id'], ['quote_line_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_line_item')
    op.drop_table('quote_line_item')
    op.drop_table('project')
    op.drop_table('quote')
    op.drop_index('idx_event_time', table_name='event')
    op.drop_index('idx_event_entity', table_name='event')
    op.drop_index('idx_event_actor', table_name='event')
    op.drop_table('event')
    op.drop_table('customer')
    op.drop_table('user')
    op.drop_index('idx_firm_benchmark_lookup', table_name='firm_benchmark')
    op.drop_table('firm_benchmark')
    op.drop_index('idx_cl_benchmark_lookup', table_name='cl_benchmark')
    op.drop_table('cl_benchmark')
    op.drop_index('idx_article_price_history_lookup', table_name='article_price_history')
    op.drop_table('article_price_history')
    op.drop_table('job_type')
    op.drop_table('firm')
    op.drop_table('article')
    # ### end Alembic commands ###
